galaxy_info:
  role_name: dotfiles
  namespace: amun
  author: Gonzalo Alvarez
  description: Install and configure dotfiles
  license: GPL-3.0
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: MacOSX
      versions:
        - all

dependencies:
  - role: utils
