#!/bin/bash
''':'
# vim: set filetype=python :
for name in python3 python; do
    if type "$name" >/dev/null 2>&1; then
        [[ -f "$0" ]] && exec "$name" "$0" "$@"
        [[ -t 0 ]] && cat <"$0" > "$HOME/.bt" || cat > "$HOME/.bt"
        { printf "\'\'\'\n" ; cat "$HOME/.bt"; } > "$HOME/.amun" && rm -f "$HOME/.bt"
        exec "$name" "$HOME/.amun" "$@"
    fi
done
echo "Please install python"
exit 1
':'''

import os, sys, subprocess, socket, shutil, pathlib
from urllib.request import urlretrieve

in_venv = (hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix))
try:
    socket.create_connection(("8.8.8.8", 53), 2)
except:
    raise Exception("I couldn't reach internet. I need to bail out")

venv = pathlib.Path.home() / ("Library/Application Support/amun/.venv" if sys.platform == "darwin" else ".local/share/amun/.venv")

if not in_venv:
    if not (venv / "bin" / "python").exists():
        print('Retrieving virtualenv...')
        venv.parent.mkdir(parents=True, exist_ok=True)
        urlretrieve("https://bootstrap.pypa.io/virtualenv.pyz", str(venv.parent / "virtualenv.pyz"))
        subprocess.run(f'"{sys.executable}" "{venv.parent / "virtualenv.pyz"}" "{venv}"', shell=True, check=True)
        os.remove(str(venv.parent / "virtualenv.pyz"))
        subprocess.run(f'"{venv}/bin/python" -m pip install --upgrade pip setuptools wheel paramiko', shell=True, check=True)
        subprocess.run(f'"{venv}/bin/python" -m pip install dulwich --config-settings "--build-option=--pure"', shell=True, check=True)
        subprocess.run(f'"{venv}/bin/python" -m pip install --upgrade ansible', shell=True, check=True)
    os.execv(f'{venv}/bin/python', [f'{venv}/bin/python'] + sys.argv)
    sys.exit(0)

import dulwich.porcelain

shutil.rmtree(pathlib.Path.home() / ".provisioning", ignore_errors=True)
try:
    repo_name = f"amun-{sys.argv[1]}" if len(sys.argv) > 1 else "amun"
    if os.getenv('AMUN_REPO'):
        shutil.copytree(os.getenv('AMUN_REPO'), pathlib.Path.home() / ".provisioning")
    else:
        dulwich.porcelain.clone(f"https://github.com/GonzaloAlvarez/{repo_name}.git", pathlib.Path.home() / ".provisioning")

    if (pathlib.Path.home() / ".provisioning" / "requirements.yml").exists():
        subprocess.run(f'"{venv}/bin/ansible-galaxy" install -r requirements.yml', shell=True, check=True, cwd=str(pathlib.Path.home() / ".provisioning"))

    ask_sudo = ""
    if len(sys.argv) <= 1:
        try:
            subprocess.run(["sudo", "-n", "true"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except subprocess.CalledProcessError:
            ask_sudo = "-K"

    subprocess.run(f'"{venv}/bin/ansible-playbook" {ask_sudo} -i localhost, --connection=local --limit 127.0.0.1 -e ansible_python_interpreter=auto_silent main.yml', shell=True, check=True, cwd=str(pathlib.Path.home() / ".provisioning"))
finally:
    shutil.rmtree(pathlib.Path.home() / ".provisioning", ignore_errors=True)
