---
- name: Configure Termux remote access
  import_tasks: termux.yml
  when: amun_is_termux | default(false)

- name: Configure standard remote access
  import_tasks: standard.yml
  when: not (amun_is_termux | default(false))
