#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# created by Tobias Powalowski <tpowa@archlinux.org>
. /usr/lib/archboot/common.sh
. /usr/lib/archboot/installer/common.sh

echo "Automatic Archboot - Arch Linux Installation:"
echo "Logging is done on ${_LOG}..."

echo "10 seconds to stop the process with CTRL-C now..."
sleep 10

### localize
echo "Localization..."
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo LC_COLLATE=C >> /etc/locale.conf
localectl set-locale "en_US.UTF-8" &>"${_NO_LOG}"
sd '(^[a-z])' '#$1' /etc/locale.gen
sd "^#en_US.UTF-8" "en_US.UTF-8" /etc/locale.gen
locale-gen &>"${_NO_LOG}"
localectl set-locale "${_LOCALE}.UTF-8" &>"${_NO_LOG}"
localectl set-x11-keymap "${_DETECTED_KEYMAP}" &>"${_NO_LOG}"
export LANG="en_US.UTF-8"
: > /.localize

### network profile
echo "Network..."
: >"/etc/systemd/network/enp0s1-ethernet.network"
{
echo "#/etc/systemd/network/enp0s1-ethernet.network generated by Archboot setup"
echo "[Match]"
echo "Name=enp0s1"
echo ""
echo "[Network]"
echo "MulticastDNS=yes"
echo "DHCP=yes"
} >>"/etc/systemd/network/enp0s1-ethernet.network"
unset "http_proxy"
unset "https_proxy"
unset "ftp_proxy"
unset "rsync_proxy"
unset "HTTP_PROXY"
unset "HTTPS_PROXY"
unset "FTP_PROXY"
unset "RSYNC_PROXY"
rm -f /etc/systemd/network/10-wired-auto-dhcp.network
systemctl restart systemd-networkd
systemctl restart systemd-resolved
echo "Waiting for network link..."
while true; do
  if getent hosts www.google.com &>"${_LOG}"; then
      break
  else
      sleep 1
  fi
done
: > /.network

### clock
echo "Clock..."
timedatectl set-timezone "America/New_York"
echo 0.0 0 0.0 > /etc/adjtime
echo 0 >> /etc/adjtime
echo UTC >> /etc/adjtime
timedatectl set-local-rtc 0
systemctl restart systemd-timesyncd
timedatectl set-ntp 1
: > /.clock

### pacman mirror
echo "Pacman Server..."
sd '^Server' '#Server' "/etc/pacman.d/mirrorlist"
echo 'Server = ' >> "/etc/pacman.d/mirrorlist"

### pacman mirror
echo "Pacman Server..."
sd '^Server' '#Server' "/etc/pacman.d/mirrorlist"
echo 'Server = http://mirror.archlinuxarm.org/$arch/$repo' >> "/etc/pacman.d/mirrorlist"

### pacman keyring
echo "Pacman keyring..."
_pacman_keyring
pacman -Sy --noconfirm --noprogressbar archlinux-keyring &>"${_LOG}"
: > /.pacsetup

### quicksetup
: > /tmp/.device-names
: > /tmp/.fstab
wipefs -a -f "/dev/nvme0n1" &>"${_NO_LOG}"
dd if=/dev/zero of="/dev/nvme0n1" bs=1M count=10 &>"${_NO_LOG}"
sync

### partition
echo "Partitioning /dev/nvme0n1..."
sfdisk "/dev/nvme0n1" << EOF &>"${_LOG}"
label: gpt
label-id: 63BCA1B0-382B-412C-8EBB-8066AF6CD2E8
device: /dev/nvme0n1
unit: sectors
first-lba: 2048
last-lba: 62914526
sector-size: 512

/dev/nvme0n1p1 : start=        2048, size=        4096, type=21686148-6449-6E6F-744E-656564454649, uuid=C854F687-98C2-4BE2-B6A6-1F26FA8A2BAA, name="BIOS_GRUB"
/dev/nvme0n1p2 : start=        6144, size=     2097152, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=91410C60-4BAB-4979-82AC-F9DF6EE0BAD7, name="ESP"
/dev/nvme0n1p3 : start=     2103296, size=     1048576, type=BC13C2FF-59E6-4262-A352-B275FD6F7172, uuid=7AC3DFFE-32E5-467E-91C9-A3353E132B8D, name="XBOOTLDR"
/dev/nvme0n1p4 : start=     3151872, size=      524288, type=0657FD6D-A4AB-43C4-84E5-0933C84B4F4F, uuid=085668AE-FC4F-4577-B0C6-2D6DD466CB89, name="SWAP"
/dev/nvme0n1p5 : start=     3676160, size=    15360000, type=B921B045-1DF0-41C3-AF44-4C6F280D3FAE, uuid=57F70297-F090-4119-8A79-D9F24A388960, name="ARCH_LINUX_ROOT"
/dev/nvme0n1p6 : start=    19036160, size=    43876352, type=933AC7E1-2EB4-4F13-B844-0E14E2AEF915, uuid=65820348-CCEA-42BB-81B0-9F250147A95E, name="ARCH_LINUX_HOME"
EOF

### quicksetup mountpoints
udevadm settle
echo "Creating and activating swapspace on /dev/nvme0n1p4..."
mkswap -L "SWAP" "/dev/nvme0n1p4" &>"${_LOG}"
swapon "/dev/nvme0n1p4" &>"${_LOG}"
echo "# DEVICE DETAILS: /dev/nvme0n1p4 PARTUUID=085668ae-fc4f-4577-b0c6-2d6dd466cb89 PARTLABEL=SWAP UUID=$(lsblk -rpno UUID /dev/nvme0n1p4) LABEL=SWAP" >> /tmp/.device-names
echo "Creating ext4 on /dev/nvme0n1p5, mounting to /mnt/install/..."
mkfs.ext4 -F -L ARCH_ROOT /dev/nvme0n1p5 &>"${_LOG}"
btrfs device scan &>"${_NO_LOG}"
mkdir -p "/mnt/install""/"
mount -t "ext4" -o "noatime" "/dev/nvme0n1p5" "/mnt/install""/" &>"${_LOG}"
echo "# DEVICE DETAILS: /dev/nvme0n1p5 PARTUUID=57f70297-f090-4119-8a79-d9f24a388960 PARTLABEL=ARCH_LINUX_ROOT UUID=$(lsblk -rpno UUID /dev/nvme0n1p5) LABEL=ARCH_ROOT" >> /tmp/.device-names
echo -n "PARTUUID=57f70297-f090-4119-8a79-d9f24a388960 / ext4 defaults,noatime 0 " >>/tmp/.fstab
echo 1 >>/tmp/.fstab
echo "Creating ext4 on /dev/nvme0n1p6, mounting to /mnt/install/home..."
mkfs.ext4 -F -L ARCH_HOME /dev/nvme0n1p6 &>"${_LOG}"
btrfs device scan &>"${_NO_LOG}"
mkdir -p "/mnt/install""/home"
mount -t "ext4" -o "noatime" "/dev/nvme0n1p6" "/mnt/install""/home" &>"${_LOG}"
echo "# DEVICE DETAILS: /dev/nvme0n1p6 PARTUUID=65820348-ccea-42bb-81b0-9f250147a95e PARTLABEL=ARCH_LINUX_HOME UUID=$(lsblk -rpno UUID /dev/nvme0n1p6) LABEL=ARCH_HOME" >> /tmp/.device-names
echo -n "PARTUUID=65820348-ccea-42bb-81b0-9f250147a95e /home ext4 defaults,noatime 0 " >>/tmp/.fstab
echo 1 >>/tmp/.fstab
echo "Creating vfat on /dev/nvme0n1p2, mounting to /mnt/install/efi..."
mkfs.vfat -F32 -n ESP /dev/nvme0n1p2 &>"${_LOG}"
btrfs device scan &>"${_NO_LOG}"
mkdir -p "/mnt/install""/efi"
mount -t "vfat" -o "" "/dev/nvme0n1p2" "/mnt/install""/efi" &>"${_LOG}"
mkdir "/mnt/install/efi/EFI"
echo "# DEVICE DETAILS: /dev/nvme0n1p2 PARTUUID=91410c60-4bab-4979-82ac-f9df6ee0bad7 PARTLABEL=ESP UUID=$(lsblk -rpno UUID /dev/nvme0n1p2) LABEL=ESP" >> /tmp/.device-names
echo -n "PARTUUID=91410c60-4bab-4979-82ac-f9df6ee0bad7 /efi vfat defaults 0 " >>/tmp/.fstab
echo 1 >>/tmp/.fstab
echo "Creating vfat on /dev/nvme0n1p3, mounting to /mnt/install/boot..."
mkfs.vfat -F32 -n XBOOTLDR /dev/nvme0n1p3 &>"${_LOG}"
btrfs device scan &>"${_NO_LOG}"
mkdir -p "/mnt/install""/boot"
mount -t "vfat" -o "" "/dev/nvme0n1p3" "/mnt/install""/boot" &>"${_LOG}"
echo "# DEVICE DETAILS: /dev/nvme0n1p3 PARTUUID=7ac3dffe-32e5-467e-91c9-a3353e132b8d PARTLABEL=XBOOTLDR UUID=$(lsblk -rpno UUID /dev/nvme0n1p3) LABEL=XBOOTLDR" >> /tmp/.device-names
echo -n "PARTUUID=7ac3dffe-32e5-467e-91c9-a3353e132b8d /boot vfat defaults 0 " >>/tmp/.fstab
echo 1 >>/tmp/.fstab

### pacman installation
_chroot_mount
mkdir -p "${_DESTDIR}/var/cache/pacman/pkg"
mkdir -p "${_DESTDIR}/var/lib/pacman"
echo "Installing base git python iptables-nft kmscon linux polkit btrfs-progs e2fsprogs dosfstools terminus-font ttf-hack-nerd..."
sleep 2
pacman --root /mnt/install --cachedir=/mnt/install/var/cache/pacman/pkg --noconfirm -Sy base git python iptables-nft kmscon linux polkit btrfs-progs e2fsprogs dosfstools terminus-font ttf-hack-nerd &>"${_LOG}"
sync
sleep 3
_chroot_umount
sleep 3
### autoconfiguration
_chroot_mount
sleep 2
mkdir -p "${_DESTDIR}/etc/systemd/network"
mkdir -p "${_DESTDIR}/etc/systemd/network.conf.d"
mkdir -p "${_DESTDIR}/etc/udev/rules.d"
mkdir -p "${_DESTDIR}/etc/sysctl.d"
mkdir -p "${_DESTDIR}/etc/profile.d"
mkdir -p "${_DESTDIR}/etc/pacman.d"
mkdir -p "${_DESTDIR}/etc/kmscon"
mkdir -p "${_DESTDIR}/etc/systemd/system/getty.target.wants"
echo "Enable timezone setting on installed system..."
cp -a /etc/localtime "${_DESTDIR}"/etc/localtime
echo "Enable clock setting on installed system..."
cp /etc/adjtime "${_DESTDIR}"/etc/adjtime
echo "Enable network and disable wifi on installed system..."
cp /etc/systemd/network/* "${_DESTDIR}"/etc/systemd/network/ &>"${_NO_LOG}"
chroot "${_DESTDIR}" systemctl enable systemd-networkd &>"${_NO_LOG}"
mkdir -p "${_DESTDIR}/etc/systemd/network.conf.d"
cp /etc/systemd/network.conf.d/ipv6-privacy-extensions.conf "${_DESTDIR}"/etc/systemd/network.conf.d/ipv6-privacy-extensions.conf
echo "Create new fstab on installed system..."
sort /tmp/.device-names >>"${_DESTDIR}"/etc/fstab
sd '^[^#]*' '' "${_DESTDIR}"/etc/fstab
sort /tmp/.fstab >>"${_DESTDIR}"/etc/fstab
echo "Enable performance ioscheduler settings on installed system..."
cp /etc/udev/rules.d/60-ioschedulers.rules "${_DESTDIR}"/etc/udev/rules.d/60-ioschedulers.rules
echo "Enable sysctl swap settings on installed system..."
cp /etc/sysctl.d/99-sysctl.conf "${_DESTDIR}"/etc/sysctl.d/99-sysctl.conf
echo "Enable pacman's GPG keyring files on installed system..."
cp -ar /etc/pacman.d/gnupg "${_DESTDIR}"/etc/pacman.d &>"${_NO_LOG}"
echo "Enable pacman mirror on installed system..."
echo 'Server = http://mirror.archlinuxarm.org/$arch/$repo' >> "${_DESTDIR}/etc/pacman.d/mirrorlist"
cp "${_DESTDIR}"/etc/kmscon/kmscon.conf.example "${_DESTDIR}"/etc/kmscon/kmscon.conf
rm "${_DESTDIR}"/etc/systemd/system/getty.target.wants/getty@tty1.service
echo "Setting keymap,font and kmscon on installed system..."
cp /etc/vconsole.conf "${_DESTDIR}"/etc/vconsole.conf
ln -s /usr/lib/systemd/system/kmsconvt@.service "${_DESTDIR}"/etc/systemd/system/autovt@.service
ln -s /usr/lib/systemd/system/kmsconvt@.service "${_DESTDIR}"/etc/systemd/system/getty.target.wants/kmsconvt@tty1.service
sd '^#hwaccel' 'hwaccel' "${_DESTDIR}"/etc/kmscon/kmscon.conf
echo "Set default hostname on installed system..."
echo "myhostname" > "${_DESTDIR}"/etc/hostname
echo "Set default locale on installed system..."
cp /etc/locale.conf "${_DESTDIR}"/etc/locale.conf
echo "Enable glibc locales based on locale.conf on installed system..."
sd "^#en_US" "en_US" "${_DESTDIR}"/etc/locale.gen
echo "Setup bash with custom options on installed system..."
cp "${_DESTDIR}"/etc/skel/.bash* "${_DESTDIR}"/root/
_chroot_umount
echo "Rebuilding glibc locales on installed system..."
systemd-nspawn -q -D /mnt/install locale-gen &>"${_NO_LOG}"

### pacman installation
_chroot_mount
echo "Installing neovim, sudo, openssh..."
pacman --root /mnt/install --cachedir=/mnt/install/var/cache/pacman/pkg --noconfirm -Sy neovim sudo openssh &>"${_LOG}"
sync
chroot "${_DESTDIR}" systemctl enable sshd &>"${_NO_LOG}"
_chroot_umount

### hwdetect
echo "Preconfiguring mkinitcpio settings on installed system..."
sd "^MODULES=.*" "MODULES=(ext4 btrfs vfat crc32c)" "${_DESTDIR}"/etc/mkinitcpio.conf
sd "^HOOKS=.*" "HOOKS=(systemd autodetect microcode modconf kms keyboard sd-vconsole block filesystems fsck)" "${_DESTDIR}"/etc/mkinitcpio.conf

### mkinitcpio
_chroot_mount
echo "Running mkinitcpio on installed system..."
chroot "${_DESTDIR}" mkinitcpio -p "linux"-"aarch64" &>"${_LOG}"
_chroot_umount

### pacman installation
_chroot_mount
echo "Installing bash-completion..."
pacman --root /mnt/install --cachedir=/mnt/install/var/cache/pacman/pkg --noconfirm -Sy bash-completion &>"${_LOG}"
sync
_chroot_umount

### default shell
sd '^SHELL=.*' "SHELL=/usr/bin/bash" "${_DESTDIR}"/etc/default/useradd
usermod -R "${_DESTDIR}" -s "/usr/bin/bash" "root" &>"${_LOG}"
echo "Default shell set to bash."

### set user password
echo "archboot" > /tmp/.password
echo "archboot" >> /tmp/.password
### add user
_chroot_mount
chroot "${_DESTDIR}" useradd -c "Archboot" -m "archboot" &>"${_LOG}"
chroot "${_DESTDIR}" usermod -aG wheel archboot
echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >> ${_DESTDIR}/etc/sudoers.d/10-wheel-nopasswd
chmod 400 "${_DESTDIR}/etc/sudoers.d/10-wheel-nopasswd"
echo "user account archboot created succesfully."

chroot "${_DESTDIR}" passwd "archboot" < /tmp/.password &>"${_NO_LOG}"
echo "New password set for archboot."
_chroot_umount
rm /tmp/.password

### Setup SSH authorized_keys for passwordless SSH
echo "Setting up SSH authorized_keys for archboot user..."
mkdir -p "${_DESTDIR}/home/archboot/.ssh"
if [ -f /tmp/test_key.pub ]; then
    cp /tmp/test_key.pub "${_DESTDIR}/home/archboot/.ssh/authorized_keys"
    chmod 700 "${_DESTDIR}/home/archboot/.ssh"
    chmod 600 "${_DESTDIR}/home/archboot/.ssh/authorized_keys"
    chown -R 1000:1000 "${_DESTDIR}/home/archboot/.ssh"
    echo "SSH authorized_keys installed for archboot user."
else
    echo "Warning: /tmp/test_key.pub not found, skipping SSH key setup."
fi

### /mnt/install/etc/vconsole.conf file
: > "/mnt/install/etc/vconsole.conf"
echo "# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed" >> /mnt/install/etc/vconsole.conf
echo "# and systemd-vconsole-setup(8). Use localectl(1) to update this file." >> /mnt/install/etc/vconsole.conf
echo "FONT=ter-v16n" >> /mnt/install/etc/vconsole.conf
echo "KEYMAP=us" >> /mnt/install/etc/vconsole.conf
echo "XKBLAYOUT=us" >> /mnt/install/etc/vconsole.conf
echo "" >> /mnt/install/etc/vconsole.conf

### /mnt/install/etc/hosts file
: > "/mnt/install/etc/hosts"
echo "# Static table lookup for hostnames." >> /mnt/install/etc/hosts
echo "# See hosts(5) for details." >> /mnt/install/etc/hosts
echo "127.0.0.1        localhost" >> /mnt/install/etc/hosts
echo "::1              localhost" >> /mnt/install/etc/hosts
echo "" >> /mnt/install/etc/hosts

### /mnt/install/etc/hostname file
: > "/mnt/install/etc/hostname"
echo "archvm" >> /mnt/install/etc/hostname
echo "" >> /mnt/install/etc/hostname

### /mnt/install/etc/resolv.conf file
: > "/mnt/install/etc/resolv.conf"
echo "# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8)." >> /mnt/install/etc/resolv.conf
echo "# Do not edit." >> /mnt/install/etc/resolv.conf
echo "#" >> /mnt/install/etc/resolv.conf
echo "# This file might be symlinked as /etc/resolv.conf. If you are looking at" >> /mnt/install/etc/resolv.conf
echo "# /etc/resolv.conf and seeing this text, you have followed the symlink." >> /mnt/install/etc/resolv.conf
echo "#" >> /mnt/install/etc/resolv.conf
echo "# This is a dynamic resolv.conf file for connecting local clients to the" >> /mnt/install/etc/resolv.conf
echo "# internal DNS stub resolver of systemd-resolved. This file lists all" >> /mnt/install/etc/resolv.conf
echo "# configured search domains." >> /mnt/install/etc/resolv.conf
echo "#" >> /mnt/install/etc/resolv.conf
echo "# Run "resolvectl status" to see details about the uplink DNS servers" >> /mnt/install/etc/resolv.conf
echo "# currently in use." >> /mnt/install/etc/resolv.conf
echo "#" >> /mnt/install/etc/resolv.conf
echo "# Third party programs should typically not access this file directly, but only" >> /mnt/install/etc/resolv.conf
echo "# through the symlink at /etc/resolv.conf. To manage man:resolv.conf in a" >> /mnt/install/etc/resolv.conf
echo "# different way, replace this symlink by a static file or a different symlink." >> /mnt/install/etc/resolv.conf
echo "#" >> /mnt/install/etc/resolv.conf
echo "# See man:systemd-resolved.service for details about the supported modes of" >> /mnt/install/etc/resolv.conf
echo "# operation for /etc/resolv.conf." >> /mnt/install/etc/resolv.conf
echo "" >> /mnt/install/etc/resolv.conf
echo "nameserver 1.1.1.1" >> /mnt/install/etc/resolv.conf
echo "options edns0 trust-ad" >> /mnt/install/etc/resolv.conf
echo "search ." >> /mnt/install/etc/resolv.conf
echo "" >> /mnt/install/etc/resolv.conf

### /mnt/install/etc/hosts file
: > "/mnt/install/etc/hosts"
echo "# Static table lookup for hostnames." >> /mnt/install/etc/hosts
echo "# See hosts for details." >> /mnt/install/etc/hosts
echo "127.0.0.1        localhost" >> /mnt/install/etc/hosts
echo "::1              localhost" >> /mnt/install/etc/hosts
echo "" >> /mnt/install/etc/hosts

### pacman installation
_chroot_mount
echo "Installing efivar efibootmgr..."
pacman --root /mnt/install --cachedir=/mnt/install/var/cache/pacman/pkg --noconfirm -Sy efivar efibootmgr &>"${_LOG}"
sync
_chroot_umount

### pacman installation
_chroot_mount
echo "Installing grub..."
pacman --root /mnt/install --cachedir=/mnt/install/var/cache/pacman/pkg --noconfirm -Sy grub &>"${_LOG}"
sync
_chroot_umount

### grub uefi
echo "Setting up GRUB(2) UEFI..."
_chroot_mount
chroot "${_DESTDIR}" grub-install --directory="/usr/lib/grub/arm64-efi" --target="arm64-efi" --efi-directory="/efi" --bootloader-id="GRUB" --recheck --debug &>"${_LOG}"
mkdir -p "${_DESTDIR}/boot/grub/fonts"
cp -f "${_DESTDIR}/usr/share/grub/ter-u16n.pf2" "${_DESTDIR}/boot/grub/fonts/ter-u16n.pf2"

### /mnt/install/boot/grub/grub.cfg file
: > "/mnt/install/boot/grub/grub.cfg"
echo '# Include modules - required for boot' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod part_gpt' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod part_msdos' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod fat' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod fat' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod ext2' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod ext2' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod search_fs_file' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod search_fs_uuid' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod search_label' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod linux' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod chain' >> /mnt/install/boot/grub/grub.cfg
echo 'set pager=1' >> /mnt/install/boot/grub/grub.cfg
echo '# set debug="all"' >> /mnt/install/boot/grub/grub.cfg
echo 'set locale_dir="${prefix}/locale"' >> /mnt/install/boot/grub/grub.cfg
echo 'if [ "${grub_platform}" == "efi" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '    insmod all_video' >> /mnt/install/boot/grub/grub.cfg
echo '    insmod efi_gop' >> /mnt/install/boot/grub/grub.cfg
echo '    if [ "${grub_cpu}" == "x86_64" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '        insmod bli' >> /mnt/install/boot/grub/grub.cfg
echo '        insmod efi_uga' >> /mnt/install/boot/grub/grub.cfg
echo '    elif [ "${grub_cpu}" == "i386" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '        insmod bli' >> /mnt/install/boot/grub/grub.cfg
echo '        insmod efi_uga' >> /mnt/install/boot/grub/grub.cfg
echo '    fi' >> /mnt/install/boot/grub/grub.cfg
echo 'elif [ "${grub_platform}" == "pc" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '    insmod vbe' >> /mnt/install/boot/grub/grub.cfg
echo '    insmod vga' >> /mnt/install/boot/grub/grub.cfg
echo '    insmod png' >> /mnt/install/boot/grub/grub.cfg
echo 'fi' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod video_bochs' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod video_cirrus' >> /mnt/install/boot/grub/grub.cfg
echo 'insmod font' >> /mnt/install/boot/grub/grub.cfg
echo 'search --fs-uuid --no-floppy --set=usr_part  b45c2645-8002-4b69-9f56-1f0022e5af83' >> /mnt/install/boot/grub/grub.cfg
echo 'search --fs-uuid --no-floppy --set=root_part  b45c2645-8002-4b69-9f56-1f0022e5af83' >> /mnt/install/boot/grub/grub.cfg
echo 'if [ -e "${prefix}/fonts/ter-u16n.pf2" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '    set _fontfile="${prefix}/fonts/ter-u16n.pf2"' >> /mnt/install/boot/grub/grub.cfg
echo 'else' >> /mnt/install/boot/grub/grub.cfg
echo '    if [ -e "(${root_part})/usr/share/grub/ter-u16n.pf2" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '        set _fontfile="(${root_part})/usr/share/grub/ter-u16n.pf2"' >> /mnt/install/boot/grub/grub.cfg
echo '    else' >> /mnt/install/boot/grub/grub.cfg
echo '        if [ -e "(${usr_part})/share/grub/ter-u16n.pf2" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '            set _fontfile="(${usr_part})/share/grub/ter-u16n.pf2"' >> /mnt/install/boot/grub/grub.cfg
echo '        fi' >> /mnt/install/boot/grub/grub.cfg
echo '    fi' >> /mnt/install/boot/grub/grub.cfg
echo 'fi' >> /mnt/install/boot/grub/grub.cfg
echo 'if loadfont "${_fontfile}" ; then' >> /mnt/install/boot/grub/grub.cfg
echo '    insmod gfxterm' >> /mnt/install/boot/grub/grub.cfg
echo '    set gfxmode="auto"' >> /mnt/install/boot/grub/grub.cfg
echo '' >> /mnt/install/boot/grub/grub.cfg
echo '    terminal_input console' >> /mnt/install/boot/grub/grub.cfg
echo '    terminal_output gfxterm' >> /mnt/install/boot/grub/grub.cfg
echo 'fi' >> /mnt/install/boot/grub/grub.cfg
echo 'set timeout=3' >> /mnt/install/boot/grub/grub.cfg
echo 'set timeout_style=menu' >> /mnt/install/boot/grub/grub.cfg
echo 'set recordfail=0' >> /mnt/install/boot/grub/grub.cfg
echo '# DEVICE DETAILS: /dev/nvme0n1p2 PARTUUID=91410c60-4bab-4979-82ac-f9df6ee0bad7 PARTLABEL=ESP UUID=8F9A-6BDB LABEL=ESP' >> /mnt/install/boot/grub/grub.cfg
echo '# DEVICE DETAILS: /dev/nvme0n1p3 PARTUUID=7ac3dffe-32e5-467e-91c9-a3353e132b8d PARTLABEL=XBOOTLDR UUID=8F9B-38DB LABEL=XBOOTLDR' >> /mnt/install/boot/grub/grub.cfg
echo '# DEVICE DETAILS: /dev/nvme0n1p4 PARTUUID=085668ae-fc4f-4577-b0c6-2d6dd466cb89 PARTLABEL=SWAP UUID=a824a2ce-2309-4e99-929c-b212ab46cb4a LABEL=SWAP' >> /mnt/install/boot/grub/grub.cfg
echo '# DEVICE DETAILS: /dev/nvme0n1p5 PARTUUID=57f70297-f090-4119-8a79-d9f24a388960 PARTLABEL=ARCH_LINUX_ROOT UUID=b45c2645-8002-4b69-9f56-1f0022e5af83 LABEL=ARCH_ROOT' >> /mnt/install/boot/grub/grub.cfg
echo '# DEVICE DETAILS: /dev/nvme0n1p6 PARTUUID=65820348-ccea-42bb-81b0-9f250147a95e PARTLABEL=ARCH_LINUX_HOME UUID=f8e02fb3-2667-4a7c-babf-a0e13dfbd270 LABEL=ARCH_HOME' >> /mnt/install/boot/grub/grub.cfg
echo '# (0) Arch Linux' >> /mnt/install/boot/grub/grub.cfg
echo 'menuentry "Arch Linux" {' >> /mnt/install/boot/grub/grub.cfg
echo '    set gfxpayload="keep"' >> /mnt/install/boot/grub/grub.cfg
echo '    search --fs-uuid --no-floppy --set=root  8F9B-38DB' >> /mnt/install/boot/grub/grub.cfg
echo '    linux /Image.gz root=PARTUUID=57f70297-f090-4119-8a79-d9f24a388960 rootfstype=ext4 rw rootflags=rw,noatime ' >> /mnt/install/boot/grub/grub.cfg
echo '    initrd /initramfs-linux.img' >> /mnt/install/boot/grub/grub.cfg
echo '' >> /mnt/install/boot/grub/grub.cfg
echo '}' >> /mnt/install/boot/grub/grub.cfg
echo 'if [ "${grub_platform}" == "efi" ]; then' >> /mnt/install/boot/grub/grub.cfg
echo '    menuentry "UEFI Firmware Setup" {' >> /mnt/install/boot/grub/grub.cfg
echo '        fwsetup' >> /mnt/install/boot/grub/grub.cfg
echo '        }' >> /mnt/install/boot/grub/grub.cfg
echo 'fi' >> /mnt/install/boot/grub/grub.cfg
echo 'menuentry "Reboot System" {' >> /mnt/install/boot/grub/grub.cfg
echo '    reboot' >> /mnt/install/boot/grub/grub.cfg
echo '}' >> /mnt/install/boot/grub/grub.cfg
echo 'menuentry "Poweroff System" {' >> /mnt/install/boot/grub/grub.cfg
echo '    halt' >> /mnt/install/boot/grub/grub.cfg
echo '}' >> /mnt/install/boot/grub/grub.cfg
echo '' >> /mnt/install/boot/grub/grub.cfg

### fixing grub uuids
_chroot_mount
_BOOTDEV_FS_UUID_OLD="8F9B-38DB"
_ROOTDEV_FS_UUID_OLD="b45c2645-8002-4b69-9f56-1f0022e5af83"
_USRDEV_FS_UUID_OLD="b45c2645-8002-4b69-9f56-1f0022e5af83"
_BOOTDEV_FS_UUID="$(chroot /mnt/install grub-probe --target="fs_uuid" "/boot" 2>"${_NO_LOG}")"
_ROOTDEV_FS_UUID="$(chroot /mnt/install grub-probe --target="fs_uuid" "/" 2>"${_NO_LOG}")"
_USRDEV_FS_UUID="$(chroot /mnt/install grub-probe --target="fs_uuid" "/usr" 2>"${_NO_LOG}")"
_ESP_DEV_FS_UUID_OLD="8F9A-6BDB"
_ESP_DEV_FS_UUID="$(chroot /mnt/install grub-probe --target="fs_uuid" "/efi" 2>"${_NO_LOG}")"
sd "${_ESP_DEV_FS_UUID_OLD}" "${_ESP_DEV_FS_UUID}" "${_DESTDIR}/boot/grub/grub.cfg"
sd "${_BOOTDEV_FS_UUID_OLD}" "${_BOOTDEV_FS_UUID}" "${_DESTDIR}/boot/grub/grub.cfg"
sd "${_ROOTDEV_FS_UUID_OLD}" "${_ROOTDEV_FS_UUID}" "${_DESTDIR}/boot/grub/grub.cfg"
sd "${_USRDEV_FS_UUID_OLD}" "${_USRDEV_FS_UUID}" "${_DESTDIR}/boot/grub/grub.cfg"
_chroot_umount

### pacman hook
mkdir -p "${_DESTDIR}"/etc/pacman.d/hooks
### /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook file
: > "/mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook"
echo '[Trigger]' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo 'Type = Package' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo 'Operation = Upgrade' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo 'Target = grub' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo '' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo '[Action]' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo 'Description = Update GRUB after upgrade...' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo 'When = PostTransaction' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo 'Exec = /usr/bin/sh -c "grub-install --directory='/usr/lib/grub/arm64-efi' --target='arm64-efi' --efi-directory='/efi' --bootloader-id='GRUB' --recheck"' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook
echo '' >> /mnt/install/etc/pacman.d/hooks/999-grub-uefi.hook

### default uefi bootloader
mkdir -p "${_DESTDIR}/efi/EFI/BOOT"
rm -f "${_DESTDIR}/efi/EFI/BOOT/BOOTAA64.EFI"
cp -f "${_DESTDIR}/efi/EFI/grub/grubaa64.efi" "${_DESTDIR}/efi/EFI/BOOT/BOOTAA64.EFI"
