---
- name: Gather facts
  setup:

- name: Download dotfiles
  git:
    repo: "https://github.com/GonzaloAlvarez/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"

- name: Download gear repo
  git:
    repo: 'https://github.com/GonzaloAlvarez/gear.git'
    dest: '{{ ansible_env.HOME }}/.gear'

- name: Install dotfiles
  ansible.builtin.shell: 
    cmd: "./setup"
    chdir: "{{ ansible_env.HOME }}/.dotfiles/"
